import type { DeskCatalog } from '../research-desk-model'

/** Synthetic Research Desk catalog shared by tests; no real strategy results. */
export const catalog: DeskCatalog = {
  engine_version: 'alphaview-research-desk-v1',
  pine_export_version: 'alphaview-pine-export-v1',
  strategies: [
    {
      id: 'buy_hold',
      label: '買入持有',
      english: 'Buy and hold',
      family: 'baseline',
      source: 'Research Desk',
      summary: '基準',
      summary_en: 'Baseline',
      params: [],
    },
    {
      id: 'sma_cross',
      label: '均線交叉',
      english: 'Moving-average crossover',
      family: 'trend',
      source: 'Research Desk',
      summary: '交叉',
      summary_en: 'Cross',
      params: [
        {
          name: 'fast',
          kind: 'int',
          label: '快線週期',
          english: 'Fast SMA',
          min: 2,
          max: 200,
          default: 20,
        },
        {
          name: 'slow',
          kind: 'int',
          label: '慢線週期',
          english: 'Slow SMA',
          min: 5,
          max: 400,
          default: 50,
        },
      ],
    },
    {
      id: 'rsi_reversion',
      label: 'RSI 均值回歸',
      english: 'RSI mean reversion',
      family: 'mean_reversion',
      source: 'Research Desk',
      summary: 'RSI',
      summary_en: 'RSI',
      params: [
        {
          name: 'period',
          kind: 'int',
          label: 'RSI 週期',
          english: 'RSI period',
          min: 2,
          max: 50,
          default: 14,
        },
        {
          name: 'entry',
          kind: 'float',
          label: '進場',
          english: 'Entry',
          min: 5,
          max: 50,
          default: 30,
        },
        {
          name: 'exit',
          kind: 'float',
          label: '出場',
          english: 'Exit',
          min: 50,
          max: 95,
          default: 70,
        },
      ],
    },
  ],
  classic_set: [
    { strategy: 'buy_hold', params: {} },
    { strategy: 'sma_cross', params: { fast: 20, slow: 50 } },
  ],
  risk_defaults: {
    initial_cash: 100000,
    fee_bps: 10,
    slippage_bps: 0,
    position_pct: 100,
    stop_loss_pct: null,
    take_profit_pct: null,
  },
  limits: { symbols: 10, configs: 24, min_window_sessions: 20, min_sample_trades: 30 },
  attribution: {
    project: 'Research Desk',
    url: 'https://github.com/Miles-Deutscher/Backtesting-Engine',
    license: 'MIT',
  },
  method: 'Synthetic method.',
  warnings: ['Synthetic warning.'],
}
